### ISSUE TITLE
Unable to load AP-OTF fonts (DecodingError NotARealInDict)

### ISSUE THREAD

**Issue by ghaaj** [gfngfn/otfed#61]
Environment: WSL2 Ubuntu 24.04

When trying to load Morisawa's AP-OTF-*.otf fonts, `otfedcli` throws the following error:
```sh
$ dune exec otfedcli ~/.satysfi/dist/fonts/MorisawaFonts/AP-OTF-RyuminPr6N-Regular.otf tables
(DecodingError NotARealInDict)
```
~/.satysfi/dist/fonts/MorisawaFonts is a symlink to %LOCALAPPDATA%\Microsoft\Windows\Fonts\MorisawaFonts in the mounted Windows file system.

Given the contents of `dictmap`, it appears that this error is thrown in `get_real_with_default` due to the value for `LongKey(31)` being `[Integer(1)]`.

https://github.com/gfngfn/otfed/blob/c11304cbe723dde8f5eb2a4096513ddc0ff26bb7/src/decodeCff.ml#L62-L67

I'm not sure why `cid_font_version` needs to be a float. From reading the [spec](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5014.CIDFont_Spec.pdf) it seems to me that `CIDFontVersion` is defined as an integer. Page 22 of the document says: 

> The %%Version comment provides the version number of this CIDFont file.
This number is an integer; Adobe recommends that it be the same number that is defined for /CIDFontVersion later in the file.
     %%Version: 1

Please note that I'm a layman in terms of typography. Thank you.

**Comment by gfngfn** [comment]
Thank you for the report! This is a great catch.

The referenced spec is actually “[_Technical Note #5176: The Compact Font Format Specification, Version 1.0_](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf)”.

I haven't encountered that error so far, but it seems that this was by chance; according to _Table 10_ on page 16, `CIDFontVersion` must be a _number_, i.e., it can be an integer as well as a (decimally encoded) real number:

![Table 10 of Technical Note #5176: The Compact Font Format Specification, Version 1.0](https://github.com/user-attachments/assets/b2f3cd73-04c1-48de-88dc-d3c91ce8e48f)

I should thereby fix this so that `otfed` can decode versions encoded as integers.

**Comment by gfngfn** [comment]
Side note: I can access RyuminPr6N-Light via Adobe CC, so I checked the `CIDFontVersion` of the font file. It was `1.2`:

```console
$ otfedcli 26143.otf cff_top 
CFF Top DICT:
  { font_name = "RyuminPr6N-Light"; version = None;
    notice =
    (Some "(c) Copyright 1989-2007 Adobe Systems Incorporated. All rights reserved. Ryumin Light is a trademark of Morisawa Inc.");
    copyright =
    (Some "Font (c) Copyright 2007 Morisawa Inc. All rights reserved.");
    full_name = (Some "Ryumin Pr6N OpenType Light");
    family_name = (Some "Ryumin Pr6N OpenType"); weight = (Some "Light");
    is_fixed_pitch = false; italic_angle = 0; underline_position = -100;
    underline_thickness = 50; paint_type = 0;
    font_bbox = { x_min = -280; y_min = -294; x_max = 1134; y_max = 1160 };
    stroke_width = 0;
    cid_info =
    (Some { registry = "Adobe"; ordering = "Japan1"; supplement = 6;
            cid_font_version = 1.2; cid_font_revision = 0; cid_font_type = 0;
            cid_count = 23058 });
    number_of_glyphs = 23058 }
```

**Comment by gfngfn** [comment]
The PR https://github.com/gfngfn/otfed/pull/62 will remedy this issue. Thank you!

**Comment by gfngfn** [comment]
I've reflected the change above in the `master` branch of SATySFi: https://github.com/gfngfn/SATySFi/pull/466

**Comment by ghaaj** [comment]
Thank you for your prompt action!
